const {test}=require('node:test');const assert=require('node:assert/strict');const C=require('../dist/core.js');
const s={...C.defaults,cutoff:'2026-08-31'};
const row=(o={})=>({id:'1',date:'2026-06-15',cc:'1682',account:'5002',accountName:'Palkka',voucher:'01',line:'1',kind:'60',description:'Palkka',debit:100000,credit:0,source:'test',sheet:'test',sourceRow:1,eligible:null,reviewed:false,note:'',...o});
test('Finnish amounts and calendar validation',()=>{assert.equal(C.money('1 234,56'),123456);assert.equal(C.money('(12,30)'),-1230);assert.equal(C.money('−1,20'),-120);assert.throws(()=>C.money('abc'));assert.equal(C.date('31.02.2026'),'');assert.equal(C.date('15.6.2026'),'2026-06-15');assert.equal(C.monthEnd('2028-02'),'2028-02-29');});
test('Salary base uses standardized costs, not posted employer contributions or ICT',()=>{const r=[row(),row({id:'2',account:'5103',debit:20000}),row({id:'3',account:'5403',debit:38000}),row({id:'4',cc:'1683',account:'5499',debit:30000})],t=C.total(r,s);assert.equal(t.a,158000);assert.equal(t.b,30000);assert.equal(t.wage,100000);assert.equal(t.salary,126440);assert.equal(t.flat,50576);assert.equal(t.basis,177016);assert.equal(t.jtf+t.future,t.basis);assert.equal(t.margin,20576);});
test('Credit adjustments and user-reviewed eligible amount',()=>{let t=C.total([row(),row({id:'2',debit:0,credit:10000,eligible:-5000})],s);assert.equal(t.actual,90000);assert.equal(t.wage,95000);});
test('Unchanged reimport ignored; changed voucher blocked',()=>{const r=row(),first=C.merge([],[r]);assert.equal(first.added,1);assert.equal(C.merge(first.rows,[r]).duplicates,1);const c=C.merge(first.rows,[{...r,debit:90000}]);assert.equal(c.conflicts.length,1);assert.equal(c.rows[0].debit,100000);});
test('Missing line number matches same original record across formats',()=>{const a=row(),b=row({id:'other',line:'',kind:''});assert.equal(C.merge([a],[b]).duplicates,1);});
test('Repeated identical lines without line number retain multiplicity',()=>{const grid=[['Päivämäärä','Kustannuspaikka','Tili','Tilin nimi','Tosite','Selite','Debet','Kredit'],['15.6.2026','1682','5002','Palkka','123','Palkka','100,00',''],['15.6.2026','1682','5002','Palkka','123','Palkka','100,00','']];const p=C.parseSheet(grid,'a','CSV');assert.equal(p.errors.length,0);assert.equal(C.merge([],p.rows).added,2);assert.equal(C.merge(p.rows,p.rows).duplicates,2);});
test('Grouped report excludes balances and preserves account context',()=>{const grid=[['01.06.2026 - 30.06.2026'],['Tositepvm','Tosite','Jnro','Tl','Selitys','Debet','Kredit'],['001682','Hanke'],['5002','Palkka',null,null,'Alkusaldo',999],['15.06.2026','60','01','60','Palkka',1000],['Tunnisteet','abc'],['Tili','Yhteensä',null,null,null,1000],[null,null,null,null,'Loppusaldo',1999],['Kustannuspaikka','Yhteensä',null,null,null,1000]];const p=C.parseSheet(grid,'a','test');assert.equal(p.rows.length,1);assert.equal(p.rows[0].debit,100000);assert.equal(p.statements[0].opening,99900);assert.equal(p.statements[0].closing,199900);assert.deepEqual(p.errors,[]);grid[8][5]=999;assert.equal(C.parseSheet(grid,'a','test').errors.length,1);});
test('Malformed dated rows produce errors, other cost centers are counted',()=>{const grid=[['Päivämäärä','Kustannuspaikka','Tili','Tosite','Selite','Debet','Kredit'],['31.02.2026','1682','5002','1','bad',100,0],['1.6.2026','9999','5002','2','other',100,0]];const p=C.parseSheet(grid,'a','CSV');assert.equal(p.errors.length,1);assert.equal(p.other,1);});
test('CSV quotes, separators, decimal commas, line breaks, BOM and export injection guard',()=>{const text='\uFEFFPäivämäärä;Selite;Debet\r\n15.6.2026;"a;\n""b""";"1 234,56"';const p=C.parseCSV(text);assert.equal(p[1][1],'a;\n"b"');assert.equal(C.money(p[1][2]),123456);assert.ok(C.csv([['=CMD()']]).includes("'=CMD()"));assert.throws(()=>C.parseCSV('a;"open'));});
test('Monthly, yearly and cumulative reports reconcile, cutoff excludes future',()=>{const rows=[row(),row({id:'2',date:'2026-07-15',debit:200000}),row({id:'3',date:'2026-09-15',debit:300000})];const mm=C.report(rows,s),yy=C.report(rows,s,'yearly'),t=C.totals(rows,s);assert.equal(mm.length,3);assert.equal(t.actual,300000);assert.equal(t.actual,yy[0].actual);assert.equal(mm.reduce((a,r)=>a+r.basis,0),t.basis);assert.equal(t.jtf+t.future,t.basis);});
test('Forecast requires explicit completed month and includes zero months',()=>{const rows=[row()];assert.equal(C.forecast(rows,C.defaults),null);const f=C.forecast(rows,s);assert.equal(f.remaining,21);assert.equal(f.actual,100000+33333*21);const own=C.forecast(rows,{...s,forecastMonthly:50000});assert.equal(own.actual,100000+50000*21);});
test('Funding stages aggregate separately including rejected zero',()=>{assert.deepEqual(C.fundingTotal([{funder:'JTF',applied:10000,decided:0,received:null},{funder:'Tulevaisuusrahasto',applied:100,decided:100,received:100}],'JTF'),{applied:10000,decided:0,received:0});});
test('Backup roundtrip and corrupt backup rejection',()=>{const a=C.empty();a.rows=[row()];assert.deepEqual(C.validateState(JSON.parse(JSON.stringify(a))),a);const b=JSON.parse(JSON.stringify(a));b.rows[0].debit='no';assert.throws(()=>C.validateState(b));const d=JSON.parse(JSON.stringify(a));d.rows.push(row());assert.throws(()=>C.validateState(d));assert.throws(()=>C.validateState({schema:9}));});
test('Opening balances detect transferred 380 euros',()=>{const st=[{cc:'1682',account:'5403',period:'2026-07',opening:0,closing:38000},{cc:'1682',account:'5403',period:'2026-08',opening:0,closing:38000}];assert.equal(C.balances(st).length,1);assert.match(C.balances(st)[0],/-380.00/);});

test('Positive and negative corrections round symmetrically',()=>{const a=C.total([row({debit:25})],s),b=C.total([row({debit:0,credit:25})],s);for(const k of ['salary','side','flat','basis','jtf','future'])assert.equal(a[k],-b[k]);});
